### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by MelissaMV** [1337r00t/BruteForce-Facebook#2]
After 20 "FAIL" attempts from the Password list these errors follow. Apparently Facebook is now blocking this Brute.

Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Terminating on signal SIGINT(2)

**Comment by 1337r00t** [comment]
Unfortunately Facebook has put an limit to the attempts 😞 .
