### ISSUE TITLE
Is this bruteforce working

### ISSUE THREAD

**Issue by vex77y** [1337r00t/BruteForce-Facebook#3]
I was just wondering if this brute force is currently working.

**Comment by AbdelXY** [comment]
Hi there,
I just tested it and I placed /ranked the correct password 5th in the password.txt file and the bruteforcer kept on going "Error"  "Error"  "Error"  "Error"  "Error"
in conclusion, it does not work

**Comment by 1337r00t** [comment]
yes it's working 😄 

but Unfortunately Facebook has put an limit to the attempts 😞 .
Error means FB Server blocks you 😢 

I've updated the tool ! test it now 🙇
