### ISSUE TITLE
It Does Not work 

### ISSUE THREAD

**Issue by AbdelXY** [1337r00t/BruteForce-Facebook#4]
Hi there,
I just tested it and I placed /ranked the correct password 5th in the password.txt file and the bruteforcer kept on going "Error"  "Error"  "Error"  "Error"  "Error"
in conclusion, it does not work

**Comment by 1337r00t** [comment]
it's working 😄 

but Unfortunately Facebook has put an limit to the attempts 😞 .
Error means FB Server blocks you 😢 

I've updated the tool ! test it now 🙇

**Comment by AbdelXY** [comment]
Thanks, i am aware of facebook limit.
I have tried it before. The maximum attempt I got was 58 tries before fb blocked me.

Ok, i will try your updated version soon and let you know. By the way, what did you change in your script?
